import org.springframework.boot.gradle.plugin.SpringBootPlugin
import java.io.ByteArrayOutputStream

/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the "Building Java & JVM projects" chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1/userguide/building_java_projects.html
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.springframework.boot") version "2.6.4" apply false
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
}

fun getAppVersion(): String {
    var stdout = ByteArrayOutputStream()
    exec {
        commandLine("git", "rev-parse", "--short", "HEAD")
        standardOutput = stdout
    }
    val commitId = stdout.toString().replace("\n", "").replace("\r", "").trim()
    stdout = ByteArrayOutputStream()
    exec {
        commandLine("git", "tag", "--points-at", commitId)
        standardOutput = stdout
    }
    val tagName = stdout.toString().replace("\n", "").replace("\r", "").trim()
    var versionName = "git-$commitId"
    if ("" != tagName) {
        versionName = tagName
    }
    return versionName
}

group = "com.ndanhkhoi"
version = getAppVersion()
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.telegram:telegrambots:5.7.1")
    implementation("org.springframework.boot:spring-boot-starter")
    compileOnly("org.projectlombok:lombok")
    annotationProcessor("org.projectlombok:lombok")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
    api("io.projectreactor:reactor-core:3.4.15")
    api("io.projectreactor.addons:reactor-extra:3.4.6")
    api("org.reflections:reflections:0.10.2")
    api("org.apache.commons:commons-lang3:3.12.0")
    api("commons-io:commons-io:2.11.0")
    api("commons-beanutils:commons-beanutils:1.9.4")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

dependencyManagement {
    imports {
        mavenBom(SpringBootPlugin.BOM_COORDINATES)
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

configure<PublishingExtension> {
    publications {
        publications.create<MavenPublication>("mavenJava") {
            groupId = "com.github.ndanhkhoi"
            artifactId = "simple-telegram-command-bot-spring-boot-starter"
            version = getAppVersion()
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri("${buildDir}/publishing-repository")
        }
    }
}

tasks.withType<Jar> {
    archiveBaseName.set("simple-telegram-command-bot-spring-boot-starter")
}

tasks {
    register("fatJar", Jar::class.java) {
        archiveBaseName.set("simple-telegram-command-bot-spring-boot-starter-full-dependencies")
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
        with(jar.get() as CopySpec)
    }
}