import org.springframework.boot.gradle.plugin.SpringBootPlugin

/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the "Building Java & JVM projects" chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1/userguide/building_java_projects.html
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.springframework.boot") version "2.6.4" apply false
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
}

java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.telegram:telegrambots:5.7.1")
    implementation("org.springframework.boot:spring-boot-starter")
    compileOnly("org.projectlombok:lombok")
    annotationProcessor("org.projectlombok:lombok")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
    api("io.projectreactor:reactor-core:3.4.15")
    api("io.projectreactor.addons:reactor-extra:3.4.6")
    api("org.reflections:reflections:0.10.2")
    api("org.apache.commons:commons-lang3:3.12.0")
    api("commons-io:commons-io:2.11.0")
    api("commons-beanutils:commons-beanutils:1.9.4")
    api("com.google.guava:guava:31.0.1-jre")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

dependencyManagement {
    imports {
        mavenBom(SpringBootPlugin.BOM_COORDINATES)
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

configure<PublishingExtension> {
    publications {
        publications.create<MavenPublication>("mavenJava") {
            groupId = "com.github.ndanhkhoi"
            artifactId = "simple-telegram-command-bot-spring-boot-starter"
            version = "0.6.2"
            from(components["java"])
            repositories {
                maven {
                    name = "GitHubPackages"
                    url = uri("https://maven.pkg.github.com/ndanhkhoi/simple-telegram-command-bot-spring-boot-starter")
                    credentials {
                        username = System.getenv("GITHUB_ACTOR")
                        password = System.getenv("GITHUB_TOKEN")
                    }
                }
            }
            pom {
                name.set("Simple Telegram Command Bot Spring Boot Starter")
                description.set("A simple-to-use library to create Telegram Long Polling Bots in Java and Spring Boot with syntax like Spring MVC")
                licenses {
                    license {
                        name.set("MIT License")
                        url.set("https://github.com/ndanhkhoi/simple-telegram-command-bot-spring-boot-starter/blob/master/LICENSE")
                    }
                }
                developers {
                    developer {
                        id.set("ndanhkhoi")
                        name.set("Nguyen Duc Anh Khoi")
                        email.set("ngducanhkhoiii@gmail.com")
                    }
                }
            }
        }
    }
}

tasks.withType<Jar> {
    archiveBaseName.set("simple-telegram-command-bot-spring-boot-starter")
    archiveVersion.set("0.6.2")
}

tasks {
    register("fatJar", Jar::class.java) {
        archiveBaseName.set("simple-telegram-command-bot-spring-boot-starter-full-dependencies")
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
        with(jar.get() as CopySpec)
    }
}
