name: Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
    branches:
    - master

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build artifact
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -Pversion=${NEW_VERSION} jar

      - name: Nexus repo publish artifact
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/
          username: ndanhkhoi
          password: ${{ secrets.SONATYPE_PASSWORD }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=io.github.ndanhkhoi
          assets: extension=jar
          filename: ./build/libs/*.jar
